version: "3.6"

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    networks:
      - internalnet
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.16.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      SERVERLESS_BASE_URL: "http://localhost:3001"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
    # volumes:
      # - ./hasura-server/migrations:/hasura-migrations
      # - ./hasura-server/metadata:/hasura-metadata
    networks:
      - internalnet
volumes:
  db_data:
  now_cache:
networks:
  internalnet:
    driver: bridge
